### ISSUE TITLE
Example of "Delivery Timeline"

### ISSUE THREAD

**Issue by fabioselau077** [JHBitencourt/timeline_tile#11]
Has example code for "Delivery Timeline"?

**Comment by fabioselau077** [comment]
Closed.
https://github.com/JHBitencourt/beautiful_timelines

Thanks for package!

**Comment by JHBitencourt** [comment]
Appreciate your comment!

Yes, some real examples are at the project you listed. The delivery layout can be found specifically here:
https://github.com/JHBitencourt/beautiful_timelines/blob/master/lib/apps/delivery_timeline.dart

Let me know if you need anything else.
