### ISSUE TITLE
Connect the lines 

### ISSUE THREAD

**Issue by thirtysixmm** [JHBitencourt/timeline_tile#21]
How do I connect the lines between two timelines. For eg: how to make the line continous in the delivery timeline? Currently it has a gap between two tiles.

**Comment by JHBitencourt** [comment]
Hey there. Thanks for the issue.

Can you provide more info (image/code) on what you're trying to do?
If you see the other examples, there are plenty with connected tiles, so I'm not sure what you mean.

Examples: https://github.com/JHBitencourt/beautiful_timelines

**Comment by thirtysixmm** [comment]
Please close this issue. The extra spacing iscoming from some other widget. When I use only timeline tiles, the lines are connecting.
