### ISSUE TITLE
How to Increase the Progress bar or Timeline?

### ISSUE THREAD

**Issue by prateekmedia** [JHBitencourt/timeline_tile#27]
I know it might be a silly question but I cannot find any reference on how to increase that bar, I can make it lets say Delivery app Timeline but how to increase the status of it without making the user refresh or restart the app. Do I have to rebuild that widget everytime? Or is their an selected Index Parameter by which I can update it easily as soon as data is received...

My situation is that I have a carousel and below that is the timeline and I want as soon as carousel item change it should change the timeline status whether decrease or increase.

Thanks in advance.

**Comment by prateekmedia** [comment]
Ok got it, we have to increase the value of indicator we used with setState like I used currentMonth so I have to set its value whenever Carousel is changed using set state, My code is below

```
onChanged: setState(){
                         currentMonth = currentPage + 1;
                     }
```

something like that.

**Comment by JHBitencourt** [comment]
Hey @prateekmedia, thanks for the issue.

That's correct, I'm glad you figure it out.
The way you will update/change the timeline UI is up to you, and works like any other widget.

Just change your data and update the screen with any state management, e.g. the simple `setState` method.

**Comment by prateekmedia** [comment]
@JHBitencourt it would be nice to also document this in readme so that new users may be able to understand this function of the timeline as I can't see any references on readme or any other examples.
