### ISSUE TITLE
How to make a dashed line?

### ISSUE THREAD

**Issue by vasilich6107** [JHBitencourt/timeline_tile#29]
Hi. Thanks for component
Is there a way to make dashed line?

**Comment by miguelflores1993** [comment]
i need it too

**Comment by gordonnchy** [comment]
i need this too

**Comment by vasilich6107** [comment]
@gordonnchy @flutteresbolivia use https://pub.dev/packages/timelines

**Comment by f1dz** [comment]
It would be great if we have this feauture

**Comment by vasilich6107** [comment]
@f1dz the latest commit was [on 10 Mar 2021]
there is no hope
