### ISSUE TITLE
Horizontal timeline

### ISSUE THREAD

**Issue by JHBitencourt** [JHBitencourt/timeline_tile#3]
Issue to evaluate the implementation of a horizontal mode:

O ---- O ------- O --- O

Would this be useful? What are the features this mode should have? What are the use cases?

**Comment by TafadzwaD** [comment]
@JHBitencourt  . It can be used to inform users in the event that they need to do sequential processes. Let's say you must do event 'a','b', 'c' , 'd', 'e' before doing event 'd'. After doing event 'a' the timeline can show 'a' as completed and then the remaining events for the whole process to be considered complete. 

The feature can act as a guide to users

**Comment by TafadzwaD** [comment]
Instead of it spanning the whole vertical screen it would be nice to have it as a horizontal one as 'a', 'b,'c' and 'd' might not be on the same screen but each process relies on the other to be considered complete

**Comment by JHBitencourt** [comment]
You described the [`Stepper`](https://api.flutter.dev/flutter/material/Stepper-class.html) that already behaves as a guide to the user, and has control over the steps to enable the next one or don't.

This feature's goal is not to have any control over the steps or indicators from the timeline, neither enable the user to navigate through it (which is the purpose of a `Stepper`). 

This should be more of a visual guide of steps, like the current vertical timelines.
