### ISSUE TITLE
Add null-safety support

### ISSUE THREAD

**Issue by ErliSoares** [JHBitencourt/timeline_tile#30]
First of all, thanks a lot for this package.

I have been in the process of migrating my app to dart 2.12.x-pre to get some basic null safety checks going. It would be nice if this package had a null safe version too. See https://dart.dev/null-safety/migration-guide

**Comment by leynier** [comment]
Any update about this guys? I could help with this.

**Comment by JHBitencourt** [comment]
Thanks for the issue!
I'll be updating the package this week to `nullsafety`.

**Comment by leynier** [comment]
> Thanks for the issue!
> I'll be updating the package this week to `nullsafety`.

Awesome!!! Thanks to you for develop and sharing this package.

**Comment by JHBitencourt** [comment]
I'm closing this issue, since the version `2.0.0` with null-safety support is now released.

https://pub.dev/packages/timeline_tile

Thanks @ErliSoares @leynier
