### ISSUE TITLE
Alignment setting for indicator

### ISSUE THREAD

**Issue by Nerogee** [JHBitencourt/timeline_tile#33]
Take vertical timelineTile for example, I need the indicator to alignment at the start of it's child. By default, indicator is center aligned. Allow users to decide indicator alignment to its child is very necessary. 

This is a nice library. thanks.

**Comment by JHBitencourt** [comment]
Hey @Nerogee !

You can already do this with the [indicatorXY](https://pub.dev/documentation/timeline_tile/latest/timeline_tile/IndicatorStyle/indicatorXY.html) property from `IndicatorStyle`.

The weather timeline aligns the indicator at 0.3 for example. As you can see [here](https://github.com/JHBitencourt/beautiful_timelines/blob/8d46f5404fcfb348132f8bc70b703f4ed99de40f/lib/apps/weather_timeline.dart#L196).

<img src="https://raw.githubusercontent.com/JHBitencourt/timeline_tile/master/screenshots/weather_timeline.png" width="200"/>

Let me know if this helped you.

**Comment by Nerogee** [comment]
@JHBitencourt yep, this helps me a lot. thanks.

**Comment by JHBitencourt** [comment]
Happy to help.
I'm closing this issue for now.
