### ISSUE TITLE
Compatibility with Font Awesome Icons

### ISSUE THREAD

**Issue by ervindobri** [JHBitencourt/timeline_tile#35]
Basically, the problem is Font Awesome Icons are not displaying.
Example attached.
I tried with another renderer, but that's not displaying other icons either.

![image](https://user-images.githubusercontent.com/56959368/118399785-7e319f00-b667-11eb-8a31-3b7d7fe697da.png)

**Comment by JHBitencourt** [comment]
Hey @ervindobri , thanks for the issue.

Maybe this could help you by now https://github.com/JHBitencourt/timeline_tile/issues/14#issuecomment-680308582.
Please let me know.

**Comment by ervindobri** [comment]
> Hey @ervindobri , thanks for the issue.
> 
> Maybe this could help you by now [#14 (comment)](https://github.com/JHBitencourt/timeline_tile/issues/14#issuecomment-680308582).
> Please let me know.

I tried adding the icons to the pubspec and it is giving the same output.
How can I make a custom indicator? I'm new to this package.

**Comment by JHBitencourt** [comment]
Which pub.dev package are you using?

For a custom indicator, you could pass [any widget](https://pub.dev/documentation/timeline_tile/latest/timeline_tile/IndicatorStyle/indicator.html) to the `indicator` property from `IndicatorStyle`.



As you can see [here](https://github.com/JHBitencourt/beautiful_timelines/blob/8d46f5404fcfb348132f8bc70b703f4ed99de40f/lib/apps/activity_timeline.dart#L254) in the football timeline example, or [here](https://github.com/JHBitencourt/beautiful_timelines/blob/8d46f5404fcfb348132f8bc70b703f4ed99de40f/lib/apps/football_timeline.dart#L261) with the activity timeline example.

**Comment by ervindobri** [comment]
> Which pub.dev package are you using?
> 
> For a custom indicator, you could pass [any widget](https://pub.dev/documentation/timeline_tile/latest/timeline_tile/IndicatorStyle/indicator.html) to the `indicator` property from `IndicatorStyle`.
> 
> As you can see [here](https://github.com/JHBitencourt/beautiful_timelines/blob/8d46f5404fcfb348132f8bc70b703f4ed99de40f/lib/apps/activity_timeline.dart#L254) in the football timeline example, or [here](https://github.com/JHBitencourt/beautiful_timelines/blob/8d46f5404fcfb348132f8bc70b703f4ed99de40f/lib/apps/football_timeline.dart#L261) with the activity timeline example.

Thanks for the reply, I managed to do it with a custom indicator, but its containers size is very small for some reason..
Changing its height/width do not work. Is there a setting maybe I skipped?
![image](https://user-images.githubusercontent.com/56959368/118406365-72a0a100-b684-11eb-97e4-8c0d9d739d19.png)

I'm closing this, since I got the help I needed.
