### ISSUE TITLE
Invalid constant value on indicatorStyle color

### ISSUE THREAD

**Issue by hericsantos** [JHBitencourt/timeline_tile#4]
Hi!

When I try change the indicator style, like color: Colors.red[900], I receive this error: Invalid constant value.

Do you know how fix that?

Thank you for that nice package!

(obs: desculpa o inglês horrível, kkkk)

**Comment by JHBitencourt** [comment]
The `Colors.red[900]` parameter is not a value that is constant and it can't be built prior to execution time.

Even if you try this with a `TextStyle`:

```dart
Text(
  'Constant value',
  style: const TextStyle(color: Colors.red[900]),
)
```

You'll get the same warning. So if you really want to use a `const` style with the coloc `Colors.red[900]`, you need to use its literal value `Color(0xFFB71C1C)`, which you can get in [the implementation](https://github.com/flutter/flutter/blob/d64884dedf3201d1cc0763426fede473ee061e97/packages/flutter/lib/src/material/colors.dart#L461).

E o inglês tá bom 😉
