### ISSUE TITLE
Make iconStyle a widget

### ISSUE THREAD

**Issue by chitgoks** [JHBitencourt/timeline_tile#6]
This way, users can have the option to even tap the icon in the indicator

or im not sure how you would do this but considering there is already an indicator property which is a widget, perhaps a callback property so that users who want to use the default indicator will be able to execute call back code when that indicator widget is clicked.

**Comment by JHBitencourt** [comment]
I don't think making `IconStyle` itself a Widget would be a good idea.

But a callback to add onTap functionality to the default indicator is definitely a good suggestion.
The question is if I should ignore it when a custom indicator is provided. Considering that this custom indicator may have its own onTap callback.

**Comment by JHBitencourt** [comment]
Since it is basically the same subject, I'll be closing this issue and keep track on #5 .
