### ISSUE TITLE
Is it possible to start some specific point of timeline?

### ISSUE THREAD

**Issue by wangjacsi** [JHBitencourt/timeline_tile#9]
is there any solution for this?

**Comment by JHBitencourt** [comment]
That's not clear to me, can you be more specific on what you are trying to achieve? If possible show a layout desired.

**Comment by acniray** [comment]
i think the question is same to me, is there any method let me scroll the timeline to the specific time?

**Comment by JHBitencourt** [comment]
@wangjacsi and @acniray 
If that's the use case, `TimelineTile` is a Widget as any other and can be used inside any scrollable widget, as of `ListView`.

With this, you can use `ScrollController` to start at any index position from the list, jumping to a specific `TimelineTile`.

[Here](https://medium.com/@diegoveloper/flutter-lets-know-the-scrollcontroller-and-scrollnotification-652b2685a4ac) you can see a tutorial on how to implement `ScrollController`.

Let me know if that is what you're looking for.

**Comment by acniray** [comment]
My problem is solved by using `ScrollController`! Tks @JHBitencourt

**Comment by JHBitencourt** [comment]
I'm closing this issue, due to inactivity from the creator.

And the solution can be achieved with `ScrollController` as explained above.
